### ISSUE TITLE
Некоторые предложения

### ISSUE THREAD

**Issue by Isalight** [zhivem/DPI-Penguin#2]
Спасибо за программу! Для удобства несколько возможных улучшений.

1. Сделать название .exe файла без нумерации версии. Для того, чтобы ярлык на программу был постоянно привязан, если было обновление.
2. Автозапуск запрета с последним выбранным конфигом при запуске программы
3. Запуск в свёрнутом виде

**Comment by zhivem** [comment]
Добавлено
