### ISSUE TITLE
How to add new configeration to default.ini?

### ISSUE THREAD

**Issue by xkajxkajx** [zhivem/DPI-Penguin#3]
Thanks for adding the English version.

I have some issues about the tool:

1. The size of the tool is a little bit big "105 MB", don't you agree?

2. When closing it , it gives me this error:
![SShot 04 11 2024@06 58 0w3](https://github.com/user-attachments/assets/b4e411a3-f7fa-4e32-bd0d-c90f8e72daec)

3.Still not full translation:
![SShot 04 11 2024@07 16 ww50](https://github.com/user-attachments/assets/d3cbb3d0-ac9e-4d76-99ce-3864926ec303)

4.How to add this batch file to the default.ini file :

@echo off
start "zapret: http,https,quic,discord" /min "winws.exe" ^
--wf-tcp=80,443 --wf-udp=443 ^
--filter-tcp=80 --hostlist="russia-blacklist.txt" --dpi-desync=fake,split2 --dpi-desync-fooling=md5sig --dpi-desync-ttl=7 --new ^
--filter-tcp=443 --hostlist-auto="autohostlist.txt" --hostlist-exclude="netrogat.txt" --dpi-desync=split --dpi-desync-split-pos=1 --dpi-desync-fooling=badseq --dpi-desync-repeats=10 --dpi-desync-ttl=4

THANK YOU! AND HAVE A NICE DAY!

**Comment by zhivem** [comment]
Fixed the translation in v1.6.5. Your configuration will look like this:
```py
[xkajxkajx configuration]
executable = {ZAPRET_FOLDER}\winws.exe
args = 
    --wf-tcp=80,443; 
    --wf-udp=443; 
    --filter-tcp=80; 
    --hostlist={BLACKLIST_FILES_0};
    --dpi-desync=fake,split2; 
    --dpi-desync-fooling=md5sig; 
    --dpi-desync-ttl=7; 
    --new; 
    --filter-tcp=443; 
    --hostlist-auto={BLACKLIST_FOLDER}\autohostlist.txt;
    --hostlist-exclude={BLACKLIST_FOLDER}\netrogat.txt; 
    --dpi-desync=split; 
    --dpi-desync-split-pos=1; 
    --dpi-desync-fooling=badseq; 
    --dpi-desync-repeats=10; 
    --dpi-desync-ttl=4;
```

Add default.ini to the very bottom

**Comment by xkajxkajx** [comment]
Thanks a lot!. Appreciate it.

**Comment by xkajxkajx** [comment]
Thanks!
